const defaultMasterProducts = [
    { id: 1, brand: "HYVA ARVM", category: "wanita", name: "Inspired by Romance Wish", price: 48000, img: "ROMANCE-WISH.jpeg", desc: "Aroma floral yang sexy dan fresh. Lembut dan feminin sepanjang hari.", notes: { top: "Floral", heart: "Cucumber", base: "Freesia" }, karakter: "bunga mentimun segar dingin lembut santai siang hari keringat", rating: { top: 5, heart: 3, base: 2, longevity: 80 }, shopeeLink: "https://shopee.co.id/hyva.arvm" },
    { id: 2, brand: "HYVA ARVM", category: "wanita", name: "Inspired by Aqua Kiss", price: 48000, img: "AQUA-KISS.jpeg", desc: "Kesegaran aquatic yang sporty. Menetralkan bau badan asam.", notes: { top: "Sea Notes", heart: "Aloe Vera", base: "Daisy" }, karakter: "laut air pantai citrus dingin segar olahraga panas matahari", rating: { top: 5, heart: 4, base: 2, longevity: 60 }, shopeeLink: "https://shopee.co.id/hyva.arvm" },
    { id: 3, brand: "HYVA ARVM", category: "wanita", name: "Inspired by Scandalous", price: 48000, img: "SCANDALOUS.jpeg", desc: "Aroma manis buah raspberry yang mewah dan elegan.", notes: { top: "Raspberry", heart: "Peony", base: "Praline" }, karakter: "buah manis elegan pesta mewah malam hari kencan", rating: { top: 4, heart: 3, base: 5, longevity: 85 }, shopeeLink: "https://shopee.co.id/hyva.arvm" },
    { id: 4, brand: "HYVA ARVM", category: "wanita", name: "Inspired by Taylor Swift", price: 48000, img: "TYLOR-SWITH.jpeg", desc: "Aroma manis buah yang ceria dan soft.", notes: { top: "Apricot", heart: "Honeysuckle", base: "Musk" }, karakter: "buah manis ceria lembut kalem sekolah kantor", rating: { top: 5, heart: 3, base: 3, longevity: 70 }, shopeeLink: "https://shopee.co.id/hyva.arvm" },
    { id: 5, brand: "HYVA ARVM", category: "wanita", name: "Inspired by Pink Chiffon", price: 48000, img: "PINK-CHIFON.jpeg", desc: "Wangi manis lembut, feminin, dan sedikit powdery.", notes: { top: "Red Pear", heart: "Tiare Flower", base: "Chiffon Musk" }, karakter: "manis bedak lembut cantik ceria feminin", rating: { top: 4, heart: 4, base: 3, longevity: 75 }, shopeeLink: "https://shopee.co.id/hyva.arvm" },
    { id: 6, brand: "HYVA ARVM", category: "unisex", name: "Inspired by Baccarat Rouge 540", price: 48000, img: "BACCART.jpeg", desc: "Kemewahan amberwood yang ikonik. Aroma sultan yang bold.", notes: { top: "Saffron", heart: "Amberwood", base: "Fir Resin" }, karakter: "mewah sultan mahal kayu hangat bold elegan", rating: { top: 4, heart: 5, base: 5, longevity: 95 }, shopeeLink: "https://shopee.co.id/hyva.arvm" },
    { id: 7, brand: "HYVA ARVM", category: "wanita", name: "Inspired by Black Opium", price: 48000, img: "BLACK-OPIUM.jpeg", desc: "Kombinasi kopi dan vanilla yang misterius.", notes: { top: "Coffee", heart: "Jasmine", base: "Vanilla" }, karakter: "kopi manis elegan malam hari pesta menggoda", rating: { top: 4, heart: 3, base: 5, longevity: 90 }, shopeeLink: "https://shopee.co.id/hyva.arvm" },
    { id: 8, brand: "HYVA ARVM", category: "wanita", name: "Inspired by Vanilla Mango", price: 48000, img: "VANILA-MANGO.jpeg", desc: "Perpaduan segar mangga tropis dan manis vanilla.", notes: { top: "Mango", heart: "Peach", base: "Vanilla" }, karakter: "mangga buah tropis segar manis siang hari", rating: { top: 5, heart: 3, base: 4, longevity: 80 }, shopeeLink: "https://shopee.co.id/hyva.arvm" },
    { id: 9, brand: "HYVA ARVM", category: "wanita", name: "Inspired by Wild Vanilla", price: 48000, img: "WILD-VANILA.jpeg", desc: "Aroma vanilla murni yang hangat dan klasik.", notes: { top: "Vanilla Bean", heart: "Sugar", base: "White Musk" }, karakter: "vanilla manis hangat kalem klasik nyaman", rating: { top: 3, heart: 3, base: 5, longevity: 85 }, shopeeLink: "https://shopee.co.id/hyva.arvm" },
    { id: 10, brand: "HYVA ARVM", category: "pria", name: "Inspired by 212 VIP Man", price: 48000, img: "212-VIP-MAN.jpeg", desc: "Aroma maskulin yang enerjik dan eksklusif.", notes: { top: "Lime", heart: "Ginger", base: "Leather" }, karakter: "pria maskulin berani segar jahe sukses modern", rating: { top: 4, heart: 4, base: 4, longevity: 80 }, shopeeLink: "https://shopee.co.id/hyva.arvm" },
    { id: 11, brand: "HYVA ARVM", category: "pria", name: "Inspired by Dunhill Blue", price: 48000, img: "DUNHIL-BLUE.jpeg", desc: "Kesegaran jeruk dan laut clean.", notes: { top: "Lychee", heart: "Rosewood", base: "Amber" }, karakter: "jeruk leci kamu segar dingin maskulin kerja", rating: { top: 5, heart: 3, base: 3, longevity: 80 }, shopeeLink: "https://shopee.co.id/hyva.arvm" },
    { id: 12, brand: "HYVA ARVM", category: "pria", name: "Inspired by Lacoste Sport", price: 48000, img: "LACOSTE-SPORT.jpeg", desc: "Aroma sangat fresh. Terbaik untuk olahraga.", notes: { top: "Grapefruit", heart: "Juniper", base: "Cedar" }, karakter: "sporty segar jeruk olahraga keringat bersih", rating: { top: 5, heart: 4, base: 2, longevity: 70 }, shopeeLink: "https://shopee.co.id/hyva.arvm" },
    { id: 13, brand: "HYVA ARVM", category: "pria", name: "Inspired by One Million Lucky", price: 48000, img: "ONE-MILION-LUCKY.jpeg", desc: "Wangi woodsy yang manis dan unik.", notes: { top: "Plum", heart: "Hazelnut", base: "Cedar" }, karakter: "kayu manis unik memikat beruntung kacang", rating: { top: 4, heart: 5, base: 4, longevity: 85 }, shopeeLink: "https://shopee.co.id/hyva.arvm" },
    { id: 14, brand: "HYVA ARVM", category: "unisex", name: "Inspired by YSL Libre", price: 48000, img: "YSL-LIBRE.jpeg", desc: "Kebebasan dalam aroma lavender mewah.", notes: { top: "Lavender", heart: "Orange Blossom", base: "Vanilla" }, karakter: "lavender bunga mewah unisex bebas berkelas", rating: { top: 4, heart: 4, base: 4, longevity: 90 }, shopeeLink: "https://shopee.co.id/hyva.arvm" },
    { id: 15, brand: "HYVA ARVM", category: "unisex", name: "PROMO BUNDLING 3 BOTOL", price: 140000, img: "bandling.WEBP", desc: "Bebas pilih 3 varian apa saja.", notes: { top: "Mix", heart: "Mix", base: "Mix" }, karakter: "promo paket hemat pilihan banyak", rating: { top: 5, heart: 5, base: 5, longevity: 100 }, shopeeLink: "https://shopee.co.id/hyva.arvm" }
];